config/routes.rb
Rails.application.routes.draw do
  namespace :api, {  format: 'json' } do
    namespace :v1 do
      resources :sessions, only: [:create]
      resources :items, only: [:index, :show] do
        member do
          post :purchase
        end
      end
    end
  end
  
  get 'users/history'
  get "users/count" => "users#count"

  devise_for :users

  get "items/count" => "items#count"

  resources :items do
    member do
      get 'purchase'
    end
  end

  root 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  mount_uploader :image, ItemImageUploader
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_save :ensure_authentication_token

  has_and_belongs_to_many :items

  def ensure_authentication_token
    if self.authentication_token.blank?
      self.authentication_token = self.generate_authentication_token
    end
  end

  def generate_authentication_token
    begin
      token = Devise.friendly_token
    end while User.exists?(authentication_token: token)
    return token
  end
end

app/controllers/api/base_controller.rb
class Api::BaseController < ActionController::Base
  protect_from_forgery with: :null_session

  before_action :authenticate_user_with_token!

  private
    def authenticate_user_with_token!
      if params[:user_email] && params[:user_token]
        if user = User.find_by(email: params[:user_email])
          if Devise.secure_compare(user.authentication_token, params[:user_token])
            sign_in user, store: false
          end
        end
      end
      unless current_user
        render json: { errors: "メールアドレスまたはトークンが間違っています" }, status: 401
      end
    end
end


# http://localhost:3000/api/v1/items.json?user_email=tanaka@tanaka.com&user_token=UTpEpAw1MWPhzzA5oyXw

# email + password    =>
#                     <= user_token1
# email + user_token1 =>
# email + user_token1 =>
#           ======= Accident ======
# email + password    =>
#                     <= user_token2
# email + user_token2 =>
# email + user_token2 =>

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < Api::BaseController

end

app/controllers/api/v1/items_controller.rb
class Api::V1::ItemsController < Api::V1::BaseController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def purchase
    @item = Item.find(params[:id])
    if @item.stock > 0
      @item.stock -= 1
      @item.save
      current_user.items << @item
      render json: { message: "購入完了" }, status: 200
    else
      render json: {errors: "売り切れです。"}, status: 402
    end
  end
end

app/controllers/api/v1/sessions_controller.rb
class Api::V1::SessionsController < Api::V1::BaseController
  skip_before_action :authenticate_user_with_token!, only: [:create]
  def create
    if params[:email] && params[:password]
      @user = User.find_by(email: params[:email])
      if @user && @user.valid_password?(params[:password])
        @user.ensure_authentication_token if @user.authentication_token.blank?
        render json: { user_token: @user.authentication_token }, status: 200
      else
        render json: { errors: "メールアドレスまたはパスワードが間違っています。" }, status: 400
      end
    else
      render json: { errors: "不正なパラメーターです。" }, status: 400
    end
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :purchase]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def purchase
    # @item.decrement(:stock)
    @item.stock -= 1
    @item.save
    current_user.items << @item
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def history
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.haml
%h2 これはフォームの部分テンプレート
%p これは文章
= form_for(@item) do |f|
  - if @item.errors.any?
    #error_explanation
      %h2
        = pluralize(@item.errors.count, "error")
        prohibited this item from being saved:
      %ul
        - @item.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :price
    %br/
    = f.number_field :price
  .field
    = f.label :image
    %br/
    = f.file_field :image
  .actions
    = f.submit

app/views/items/edit.html.haml
%h1 Editing Item
= render 'form'
= link_to 'Show', @item
|
= link_to 'Back', items_path

app/views/items/history.html.haml
%h1 購入履歴
- current_user.items.each do |item|
  = item.name

app/views/items/index.html.haml
.row.text-center
  - @items.each do |item|
    .col-md-4
      = image_tag item.image_url, width: '250px'
      %h3= item.name
      %p
        = item.price
        円 - 在庫数:#{item.stock}
      %p
        - if current_user
          = link_to '購入', purchase_item_path(item), data: { confirm: '本当に購入しますか？' }, class: 'btn btn-warning'
        = link_to '商品ページへ', item, class: 'btn btn-info'

app/views/items/new.html.haml
%h1 New Item
= render 'form'
= link_to 'Back', items_path

app/views/items/purchase.html.haml
= @item.name
を購入しました。
残りの在庫数は#{@item.stock}です。

app/views/items/show.html.haml
.row.text-center
  .col-md-12
    = image_tag '/pan.jpeg', width: '250px'
    %h3= @item.name
    %p
      = @item.price
      円 - 在庫数:#{@item.stock}
  - if current_user
    = link_to '購入', purchase_item_path(@item), data: { confirm: '本当に購入しますか？' }, class: 'btn btn-warning'
  - else
    ログインをして購入してください。
- if @item.users.count != 0
  こんな人がこの商品買ってます。
  - @item.users.each do |user|
    %p= user.email

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title EcSiteForEx
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      .row{:style => "margin-bottom: 20px"}
        .col-md-6.text-left
          %h3= link_to 'パン屋さん.com', root_path
        .col-md-6.text-right
          - if current_user
            %p
              ようこそ#{current_user.email}さん
              あなたのidは#{current_user.id}です。
            %p= link_to 'ログアウト', destroy_user_session_path, class: 'btn btn-danger', method: :delete
            %p= link_to "購入履歴へ", users_history_path
          - else
            = link_to '新規登録', new_user_registration_path, class: 'btn btn-danger'
            = link_to 'ログイン', new_user_session_path, class: 'btn btn-primary'
      = yield

app/views/users/history.html.haml
%h1 購入履歴
- current_user.items.each do |item|
  = item.name